### ISSUE TITLE
Add support for using password protected Esri Secure License Files (ESLF) in disconnected environments

### ISSUE THREAD

**Issue by cameronkroeker** [Esri/arcgis-gitops#90]
A common ArcGIS Server license file type for disconnected environments, is `.ESLF`. The ESLF license file is still passed in via `server_authorization_file_path` but when its password protected it requires the password to be passed in via the `authorization_options` parameter.

These can be password protected which requires an additional parameter to be passed in via the `authorization_options`. 

- https://github.com/ArcGIS/arcgis-gitops/blob/main/config/aws/arcgis-enterprise-base-windows/application.tfvars.json
- https://github.com/ArcGIS/arcgis-gitops/blob/main/config/aws/arcgis-enterprise-base-linux/application.tfvars.json
- https://github.com/ArcGIS/arcgis-gitops/blob/main/config/aws/arcgis-server-linux/application.tfvars.json

**Comment by pbobov** [comment]
This fix adds "server_authorization_options" input variable to enterprise-base-linux-aws-application, enterprise-base-windows-aws-application, and server-linux-aws-application workflows. Value of "server_authorization_options" is added at the end of ArcGIS Server's software authorization command line.
