### ISSUE TITLE
After upgrading ArcGIS Enterprise on Kubernetes, a new backup store needs to be registered.

### ISSUE THREAD

**Issue by cameronkroeker** [Esri/arcgis-gitops#91]
Backup and restores were successful with ArcGIS Enterprise on Kubernetes 11.2:

![image](https://github.com/ArcGIS/arcgis-gitops/assets/48299621/7bdaf0eb-89d9-40da-8680-bf5e88488e0e)

![image](https://github.com/ArcGIS/arcgis-gitops/assets/48299621/f527115c-44e2-4161-b386-867e9828478c)

However, after upgrading to 11.3 the backup store is removed from Manager UI:

<img width="2547" alt="Screenshot 2024-06-27 at 9 20 48 AM" src="https://github.com/ArcGIS/arcgis-gitops/assets/48299621/a663f4b9-4b71-4ef9-b3a8-faaa2c93fce5">

"We can't upgrade the Ozone cluster in-place since it wouldn't play nice with previous versions, the alternative we put in place is forcing an admin to register a new store via the Manager UI and we documented it in the upgrade considerations."

I re-ran the enterprise-k8s-aws-backup workflow, which completed successfully. The backup is in the bucket, and even shows up in the admin api:

![image](https://github.com/ArcGIS/arcgis-gitops/assets/48299621/9a687c0e-409b-45f2-af44-5b2995953563)

It does not however show up in the Manager UI. I tried changing this value thinking it would register a new backup store but it failed.

https://github.com/ArcGIS/arcgis-gitops/blob/cf779c2f7acdbf86e27b9d25a9fa6e53744e7853/config/aws/arcgis-enterprise-k8s/backup.vars.json#L8

<img width="877" alt="Screenshot 2024-06-27 at 10 13 43 AM" src="https://github.com/ArcGIS/arcgis-gitops/assets/48299621/f5a2c2d5-8d04-44cf-ae66-d677e8f5f939">

**Comment by pbobov** [comment]
This fix:
1. Makes enterprise-k8s-aws-organization workflow to register new S3 backup stores on upgrades.
2. Adds version number to backup store root directories.
3. Makes enterprise-k8s-aws-backup and enterprise-k8s-aws-restore workflows use default backup store if "store" input variable is  `null`.
4. Adds "The admin_password value must contain at least one special character." requirement validation in enterprise-k8s-aws-organization workflow.
